# Copyright 2023 NWChemEx-Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: .github Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  Common-Pull-Request:
    uses: NWChemEx/.github/.github/workflows/common_pull_request.yaml@master
    with:
      config_file: '.github/.licenserc.yaml'
      source_dir: ''
      compilers: ''
      doc_target: 'sphinx'
    secrets: inherit

  # This will be removed/replaced in later updates
  Test-Stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Python Tests
        run: |
          python tests/python/test_pluginplayer.py